kotlin.code.style=official

group=no.nav.helsearbeidsgiver
version=0.8.1

# Plugin versions
kotlinVersion=2.2.20
kotlinterVersion=5.2.0

# Dependency versions
kotestVersion=6.0.3
kotlinxCoroutinesVersion=1.10.2
kotlinxSerializationVersion=1.9.0
ktorVersion=3.3.1
mockkVersion=1.14.6
utilsVersion=0.10.1
