kotlin.code.style=official

group=no.nav.helsearbeidsgiver
version=0.9.0

# Plugin versions
kotlinVersion=2.4.0
kotlinterVersion=5.7.0

# Dependency versions
kotestVersion=6.0.7
kotlinxCoroutinesVersion=1.10.2
kotlinxSerializationVersion=1.11.0
ktorVersion=3.5.1
mockkVersion=1.14.11
utilsVersion=0.10.1
